<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hypa_gazebo</name>
  <version>0.0.0</version>
  <description>Gazebo-specific implementations for the hypa project</description>
  <maintainer email="sheng.xin.yu@faxmail.com">Xinyu Sheng</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Qt5 system dependencies required by GUI plugin -->
  <build_depend>qtbase5-dev</build_depend>
  <build_depend>qtdeclarative5-dev</build_depend>
  <build_depend>libqcustomplot-dev</build_depend>

  <exec_depend>qtbase5-dev</exec_depend>
  <exec_depend>qtdeclarative5-dev</exec_depend>
  <exec_depend>libqcustomplot-dev</exec_depend>

  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>ros_gz_bridge</depend>
  <depend>ros_gz_sim</depend>

  <!-- GUI 插件依赖 -->
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>sensor_msgs</depend>
  <depend>rcl_interfaces</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>

  <test_depend>ament_lint_auto</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>