<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hypa_launch</name>
  <version>2.0.0</version>
  <description>HYPA功能模块启动包 - 提供功能级启动配置</description>
  <maintainer email="sheng.xin.yu@faxmail.com">Xinyu Sheng</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>hypa_bringup</exec_depend>
  <exec_depend>hypa_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>