<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>hwt9053_can_driver</name>
    <version>0.0.1</version>
    <description>HWT9053 CAN IMU 传感器驱动，通过 ROS2 SocketCAN 接口读取 IMU 数据</description>
    <maintainer email="sheng.xin.yu@faxmail.com">Xinyu Sheng</maintainer>
    <license>Proprietary</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>rclcpp</depend>
    <depend>rclcpp_lifecycle</depend>
    <depend>sensor_msgs</depend>
    <depend>ros2_socketcan</depend>
    <depend>can_msgs</depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>